<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Sample Page Test</name>
   <tag></tag>
   <elementGuidId>33ad43f7-6619-475a-a61b-7daac3b62eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Sample Page Test&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d61bc063-bc0e-4ca0-9af4-b3d2b9fb04b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sample Page Test</value>
      <webElementGuid>d1d9b5aa-65c0-4565-868a-32b9e00a3a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fb3552d99c58948e2bb074c2caec7792</value>
      <webElementGuid>01f458c1-6139-47e2-b938-04fe8c52abca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>95225655-ec22-4c6f-bbb5-e6b63f261e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>0f27cd86-fd07-4855-aa4d-2e4a75c7b2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Sample Page Test' or . = 'Sample Page Test')]</value>
      <webElementGuid>5b0eb877-affe-4e4c-9f9c-bcacbb5479b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
