<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email(required)</name>
   <tag></tag>
   <elementGuidId>7fcea51e-b043-4643-b709-a907f3fb994d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;g2599-email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'g2599-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email(required)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1a9187f-b409-47af-97a3-b810d9061712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e5757969-2f8a-475d-9fe6-7216102229b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g2599-email</value>
      <webElementGuid>00e158c3-5d94-4fdb-a137-f96aae16ab5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g2599-email</value>
      <webElementGuid>6adeae83-a8a6-4d29-80c9-7244aa7f8702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-bind--aria-invalid</name>
      <type>Main</type>
      <value>state.fieldHasErrors</value>
      <webElementGuid>1614e21c-6bb6-43fd-b3e7-222de8c80285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-bind--value</name>
      <type>Main</type>
      <value>state.getFieldValue</value>
      <webElementGuid>b072322a-e716-4bad-a15a-e2dcf1b94b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>g2599-email-email-error-message</value>
      <webElementGuid>206de75a-c8ea-48eb-8e4b-90cd8f9cc251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-on--input</name>
      <type>Main</type>
      <value>actions.onFieldChange</value>
      <webElementGuid>832d9688-8c99-4ee6-be21-337f7369812b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-on--blur</name>
      <type>Main</type>
      <value>actions.onFieldBlur</value>
      <webElementGuid>718f4b56-2bed-48ec-8098-47ec0e7c7232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-class--has-value</name>
      <type>Main</type>
      <value>state.hasFieldValue</value>
      <webElementGuid>5b0fb345-5880-497a-b9e8-b1c995593abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email  grunion-field</value>
      <webElementGuid>abcaa9dd-9eb3-4e3d-8dd7-f382ed5b5b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>137ae355-4f87-404b-be46-1e5b8794dc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15d9df06-5763-492a-bc04-e0a99e4bb3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52b0053f-77ff-45cf-bad9-89836cf96fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e297770e274a78633ae6b02f9541bfc1</value>
      <webElementGuid>dc7fc903-202e-42da-93de-a53da83ee75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'g2599-email']</value>
      <webElementGuid>3f2079a7-fad4-4b5f-9338-8f8fa437e37c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'g2599-email']</value>
      <webElementGuid>7390d116-d164-4201-93a0-a535b988e92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'g2599-email' and @id = 'g2599-email']</value>
      <webElementGuid>3b4dafbc-5d36-44e3-a824-00ed687b18b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
