<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name(required)</name>
   <tag></tag>
   <elementGuidId>d89f2399-1a90-40fd-a406-4a1c66598635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;g2599-name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'g2599-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Name(required)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92c5c6e8-7eed-4c26-b180-2184c0d1eb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad4ed495-73d1-4d24-8714-0e97e71702de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g2599-name</value>
      <webElementGuid>d8c77bda-8817-4798-bbb6-5b1f1a5cbf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g2599-name</value>
      <webElementGuid>f45806a1-0051-41a8-a505-ac8be4a421f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-bind--aria-invalid</name>
      <type>Main</type>
      <value>state.fieldHasErrors</value>
      <webElementGuid>d243b5aa-a9f8-497d-8bab-64cb090e57c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-bind--value</name>
      <type>Main</type>
      <value>state.getFieldValue</value>
      <webElementGuid>182681cc-4f1b-42a7-b8fc-c82b8c087c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>g2599-name-text-error-message</value>
      <webElementGuid>90f12c88-d529-43d9-8e34-b81a1d7e24ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-on--input</name>
      <type>Main</type>
      <value>actions.onFieldChange</value>
      <webElementGuid>b70f0449-4dd7-46ed-b85d-7ee9ca33a8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-on--blur</name>
      <type>Main</type>
      <value>actions.onFieldBlur</value>
      <webElementGuid>0b6bd7e0-051a-45c7-88e9-023741972219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-class--has-value</name>
      <type>Main</type>
      <value>state.hasFieldValue</value>
      <webElementGuid>a93e9db4-17ba-4556-b0cc-fba59f609262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name  grunion-field</value>
      <webElementGuid>dec147a2-a3c4-4317-80be-2f50a1551b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c565cbe-c074-40a9-aa0b-f371f35b0fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3714f18e-38b6-40f0-a74a-d539e6920c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4f706738-ab6c-4949-8f74-cf620aefc599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8a3e76ea60d0705c6b09b8cf3769a7b5</value>
      <webElementGuid>5441381d-0fdf-4e14-97bf-21599468adb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'g2599-name']</value>
      <webElementGuid>17603679-bf51-42c5-ada0-4b54ff3c7b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'g2599-name']</value>
      <webElementGuid>e0aa83e4-9024-484b-aa7a-e230d0a88790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'g2599-name' and @id = 'g2599-name']</value>
      <webElementGuid>de3276b2-6b61-4e7b-8d4a-e29a2dbbeab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
