<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Experience (In Years)(required)</name>
   <tag></tag>
   <elementGuidId>6bf26ab0-ce5b-4f03-8f64-3923c60207ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;g2599-experienceinyears&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'g2599-experienceinyears']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Experience (In Years)(required)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a69e0021-b5c7-4747-bd74-99979a4d86c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g2599-experienceinyears</value>
      <webElementGuid>0355d74b-c609-494a-a255-c7815a876aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g2599-experienceinyears</value>
      <webElementGuid>e822a0e8-e559-4415-b99a-f2a4d79445fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>695dd52e-a4ad-43f3-af9a-eeeb383db8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-on--change</name>
      <type>Main</type>
      <value>actions.onFieldChange</value>
      <webElementGuid>eeeb560d-08e7-4839-9ccd-37cb4705843d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wp-bind--aria-invalid</name>
      <type>Main</type>
      <value>state.fieldHasErrors</value>
      <webElementGuid>d1e9e2a1-5845-4227-95de-ecede64f244d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22dcc796-e66d-4434-b0ef-52486001dec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		0-1
		1-3
		3-5
		5-7
		7-10
		10+
	</value>
      <webElementGuid>b024b580-dcfb-4378-8a7e-3a0a58498da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-93274efb808b64429853d818a655936e</value>
      <webElementGuid>96ced74c-7d2c-4317-81d2-04ca3f3b68a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'g2599-experienceinyears']</value>
      <webElementGuid>5421f5dc-3903-4409-ad08-67558c920ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'g2599-experienceinyears']</value>
      <webElementGuid>3271a56e-4d50-4ab1-ae96-415772892b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'g2599-experienceinyears' and @id = 'g2599-experienceinyears' and (text() = '
		0-1
		1-3
		3-5
		5-7
		7-10
		10+
	' or . = '
		0-1
		1-3
		3-5
		5-7
		7-10
		10+
	')]</value>
      <webElementGuid>999b636a-c15d-43dc-9caa-61afaa93dc2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
