<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Animals</name>
   <tag></tag>
   <elementGuidId>f633b68e-7e09-4d8a-a748-36da3a21f43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primary_nav_wrap > ul > li:nth-child(2) > [href=&quot;\#&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'primary_nav_wrap']/ul/*[(name() = 'li') and (position() = 2)]/*[@href = '#']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Animals&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a356c85-85d6-4107-8167-00e7764b7381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e457d029-1e9e-4847-bd12-a30860612004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Animals</value>
      <webElementGuid>f84e718f-3574-4c4d-bab3-da783d10cb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2fe7eb3b0004d2a769b202a3bad52941</value>
      <webElementGuid>68ae0c58-99a8-45d2-b330-d523443ce278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'primary_nav_wrap']/ul/*[(name() = 'li') and (position() = 2)]/*[@href = '#']</value>
      <webElementGuid>d03d7027-b101-4df0-bf61-7cad8e56c223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'primary_nav_wrap']/ul/*[(name() = 'li') and (position() = 2)]/*[@href = '#']</value>
      <webElementGuid>f64e037e-7a7d-4071-80fd-96d164c11934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Animals' or . = 'Animals')]</value>
      <webElementGuid>37007662-40a5-43c4-95de-633c586aa3cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
