<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_cars</name>
   <tag></tag>
   <elementGuidId>dfa7ad4f-356f-42f6-82aa-5715c01cc27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cars']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cars</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ef0c91f-0d94-4b71-94d6-86748872296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>76d3ac08-5e23-41be-8a5e-668d7220f62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>0f996617-d017-4717-9ace-be89523c070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Audi
                        BMW
                        Ford
                        Honda
                        Jeep
                        Mercedes
                        Suzuki
                        Volkswagen
                     </value>
      <webElementGuid>06f36c86-3cd3-4d1b-8d8f-fee8839faeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-540b67568b66ddf0239269f586199125</value>
      <webElementGuid>ad06c2d5-ae65-4306-a211-ff1238eaf216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cars']</value>
      <webElementGuid>b63bb84c-cfcb-48f9-881c-a5c31078317d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cars']</value>
      <webElementGuid>890bd110-39ce-4728-a76d-9e6cbcb20699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cars' and @id = 'cars' and (text() = '
                        Audi
                        BMW
                        Ford
                        Honda
                        Jeep
                        Mercedes
                        Suzuki
                        Volkswagen
                     ' or . = '
                        Audi
                        BMW
                        Ford
                        Honda
                        Jeep
                        Mercedes
                        Suzuki
                        Volkswagen
                     ')]</value>
      <webElementGuid>e27fe883-740d-4a95-8dad-a20086b0ebe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
